Prevent conflicts to ensure eth iface is assigned to one firewalld zone
Related progress ticket: https://progress.opensuse.org/issues/178906
This commit will resolve duplicate ethernet interface getting set in two
firewalld zones via os-autoinst-setup-multi-machine script and resolve
potential configuration error:

```
ERROR: INVALID_INTERFACE: Zone 'public': interface 'eth0' already bound
to zone 'trusted'
```