trying to fix early death of qemu thread
The crash we see is the following:

||| finished shutdown shutdown at 2015-12-04 14:39:29 (19 s)
isotovideo done
waitpid for 26049 returned 0
sending TERM to qemu pid: 26049
waitpid for 26049 returned 26049
QEMU: qemu: terminating on signal 15 from pid 26039
sending magic and exit
ERROR: timeout reading JSON reply: Inappropriate ioctl for device
 at /usr/lib/os-autoinst/backend/driver.pm line 243.
	backend::driver::_read_json('GLOB(0x4995b20)') called at
/usr/lib/os-autoinst/backend/driver.pm line 183
	backend::driver::_send_json('backend::driver=HASH(0x13d3f10)',
'HASH(0x7ae1ce8)') called at /usr/lib/os-autoinst/backend/driver.pm line
163
	backend::driver::__ANON__('backend::driver=HASH(0x13d3f10)')
called at /usr/lib/os-autoinst/backend/driver.pm line 111
	backend::driver::stop_thread('backend::driver=HASH(0x13d3f10)')
called at /usr/lib/os-autoinst/backend/driver.pm line 75
	backend::driver::stop('backend::driver=HASH(0x13d3f10)') called
at /usr/lib/os-autoinst/bmwqemu.pm line 362
	bmwqemu::stop_vm() called at /usr/bin/isotovideo line 165
Perl exited with active threads:
	1 running and unjoined
	1 finished and unjoined
	0 running and detached

So my assumption is that thread 0 sends a stop_vm to the thread 1,
which sends the magic and exists, leaving his sockets in unknown state.

So we should actually not try to read from the socket once it's magified