Make it possible to run more than one python test module
Before all functions would be imported to the global namespace.

Issue: https://progress.opensuse.org/issues/132656

I had to rename test.py to pythontest.py because otherwise python was
complaining:

    ImportError: Module 'test' is not installed.